import {
  Cloud,
  Container,
  Terminal,
  Code2,
  Workflow,
  Server,
  Activity,
  Gauge,
  DollarSign,
  Map,
} from "lucide-react";
import { Project, Stat } from "./types";

export const projects: Project[] = [
  {
    id: "designers-cafe",
    name: "Designers' Cafe",
    status: "running",
    type: "AWS Three-Tier",
    tech: ["Astro", "Node.js", "PostgreSQL", "AWS"],
    location: "ap-southeast-2 (Sydney)",
    uptime: "99.8%",
    responseTime: "245ms",
    requests: "1.2K",
    icon: Cloud,
    color: "from-orange-500 to-red-500",
    bgGlow: "bg-orange-500/5",
    demoUrl: "http://3.106.231.215:8081",
    githubUrl: "https://github.com/KpG782/designers-cafe",
    description:
      "Coffee shop website on AWS with EC2 (t2.micro), S3 storage, RDS PostgreSQL - 3-tier architecture demonstrating cloud infrastructure deployment",
    deployment: "AWS Free Tier",
    region: "Sydney",
    cost: "$0.85/mo",
  },
  {
    id: "springboot-api",
    name: "SpringBoot REST API",
    status: "running",
    type: "Docker Multi-Stage",
    tech: ["Java 21", "Spring Boot 3.5", "Maven", "H2"],
    location: "VPS - Easypanel",
    uptime: "99.9%",
    responseTime: "89ms",
    requests: "3.5K",
    icon: Container,
    color: "from-green-500 to-emerald-600",
    bgGlow: "bg-green-500/5",
    demoUrl: "https://springboot-app.kygozf.easypanel.host",
    githubUrl: "https://github.com/KpG782/springboot-restful-webservices",
    description:
      "RESTful API with Spring Boot Actuator, zero-downtime deployment, exposed port 8080 with Let's Encrypt SSL - demonstrating production-grade containerization",
    deployment: "Easypanel VPS",
    region: "Singapore",
    cost: "Shared VPS",
  },
  {
    id: "kubectl-dev",
    name: "kubectl.dev",
    status: "running",
    type: "K8s Learning Platform",
    tech: ["Next.js 16", "TypeScript", "Tailwind v4", "Kubernetes"],
    location: "VPS - Easypanel",
    uptime: "99.7%",
    responseTime: "125ms",
    requests: "890",
    icon: Terminal,
    color: "from-blue-500 to-cyan-500",
    bgGlow: "bg-blue-500/5",
    demoUrl: "https://certificate-kubectldev.kygozf.easypanel.host",
    githubUrl: "https://github.com/KpG782/kubectl-dev",
    description:
      "Terminal-themed Kubernetes tutorial platform covering Minikube setup, kubectl exec commands, and WordPress+MySQL deployment with WCAG AA accessibility compliance",
    deployment: "Easypanel VPS",
    region: "Singapore",
    cost: "Shared VPS",
  },
  {
    id: "certifikit",
    name: "CertifiKit",
    status: "running",
    type: "Full-Stack SaaS",
    tech: ["Next.js 14", "PostgreSQL", "Docker", "n8n"],
    location: "VPS - Easypanel",
    uptime: "99.6%",
    responseTime: "156ms",
    requests: "2.1K",
    icon: Code2,
    color: "from-purple-500 to-pink-500",
    bgGlow: "bg-purple-500/5",
    demoUrl: "https://certificate-certifikit.kygozf.easypanel.host",
    githubUrl: "https://github.com/KpG782/certifikit",
    description:
      "Modern certificate generator with drag-and-drop editor, PostgreSQL database (port 5432), and n8n webhook automation for automated certificate delivery",
    deployment: "Easypanel VPS",
    region: "Singapore",
    cost: "Shared VPS",
  },
  {
    id: "containerquest",
    name: "ContainerQuest",
    status: "running",
    type: "Educational Quiz App",
    tech: ["Next.js 14", "TypeScript", "Tailwind CSS", "Docker"],
    location: "VPS - Easypanel",
    uptime: "99.9%",
    responseTime: "98ms",
    requests: "1.8K",
    icon: Workflow,
    color: "from-indigo-500 to-blue-600",
    bgGlow: "bg-indigo-500/5",
    demoUrl: "https://certificate-container-quest.kygozf.easypanel.host",
    githubUrl: "https://github.com/KpG782/container-quest",
    description:
      "Interactive quiz app on port 3000 teaching containerization vs virtualization with 10 research-backed questions, zero-downtime deployment enabled",
    deployment: "Easypanel VPS",
    region: "Singapore",
    cost: "Shared VPS",
  },
  {
    id: "terraquest",
    name: "TerraQuest",
    status: "running",
    type: "3D Learning Platform",
    tech: ["Next.js 16", "React Three Fiber", "GSAP", "Zustand"],
    location: "Vercel - Edge Network",
    uptime: "99.9%",
    responseTime: "142ms",
    requests: "850",
    icon: Map,
    color: "from-violet-500 to-purple-600",
    bgGlow: "bg-violet-500/5",
    demoUrl: "https://terraquest-zeta.vercel.app/",
    githubUrl: "https://github.com/KpG782/terraquest",
    description:
      "Interactive 3D map for learning Terraform with 9 geographical regions, cinematic camera animations, and gamified progress tracking - transforming IaC education into an immersive journey",
    deployment: "Vercel Edge",
    region: "Global CDN",
    cost: "Free Tier",
  },
];

export const stats: Stat[] = [
  {
    label: "Services",
    value: "6",
    subtext: "All Running",
    icon: Server,
    color: "from-green-400 to-green-500",
    bgColor: "bg-green-500/10",
    trend: "100%",
    trendUp: true,
  },
  {
    label: "Uptime",
    value: "99.8%",
    subtext: "Last 30 Days",
    icon: Activity,
    color: "from-blue-400 to-blue-500",
    bgColor: "bg-blue-500/10",
    trend: "Stable",
    trendUp: true,
  },
  {
    label: "Response",
    value: "142ms",
    subtext: "Average",
    icon: Gauge,
    color: "from-purple-400 to-purple-500",
    bgColor: "bg-purple-500/10",
    trend: "Fast",
    trendUp: true,
  },
  {
    label: "Cost",
    value: "$2.00",
    subtext: "Per Month",
    icon: DollarSign,
    color: "from-orange-400 to-orange-500",
    bgColor: "bg-orange-500/10",
    trend: "Low",
    trendUp: true,
  },
];
